sudo: false
language: ruby
cache:
  - bundler
  - directories:
    - "$HOME/.m2"
jdk:
  - oraclejdk8
rvm:
  - jruby-1.7.25
  - jruby-9.1.5.0
before-install: []
script:
- gem list
- bundle exec rspec spec
env:
- JRUBY_OPTS="--debug"
addons:
