sudo: false
language: ruby
cache:
  - bundler
  - directories:
    - "$HOME/.m2"
jdk:
  - oraclejdk8
rvm:
  - jruby-1.7.25
  - jruby-9.1.5.0
before-install: []
script:
- bundle exec gem list
- bundle exec rspec spec
- CODECLIMATE_REPO_TOKEN=1bdb0cb47f17fba171838cb8f4e3fa8f2a84a9980e6c042e967e7120c7b97202 bundle exec codeclimate-test-reporter
env:
- JRUBY_OPTS="--debug"
addons:
    code_climate:
        repo_token:1bdb0cb47f17fba171838cb8f4e3fa8f2a84a9980e6c042e967e7120c7b97202
